export const Questions = [
  {
    id: 1,
    question: " Choose out of the words below ",
    option: {
      'a': "white dozen eggs ",
      'b': "a dozen white ",
      'c': " a white dozen eggs ",
      'd': "dozen white",
    },
    passage: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quis amet inventore quam? Itaque cupiditate accusantium quis. Minima, aperiam. Sed ea sapiente, hic quasi aperiam recusandae dolor repellat aspernatur corporis!",
    image: "",
    answer: "b",
    modal: 'passage',
    solution: "",
    examtype: "utme",
    subject: 'Hausa',
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleChoice",
    category: "Education",
  },
  {
    id: 2,
    question: " Nigerian flag consists of 2 colours ",
    option: { 'a': "true ", 'b': "false " },

    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    subject: 'Mathematics',
    examyear: "2003",
    questionNub: 0,
    questionType: "trueOrFalse",
    category: "Education",
  },
  {
    id: 3,
    question: " He put_____  eggs in a basket.",
    option: {
      'a': "white dozen eggs ",
      'b': "a dozen white ",
      'c': " a white dozen eggs ",
      'd': " dozen white",
    },
    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    subject: 'Igbo',
    examyear: "2003",
    questionNub: 0,
    questionType: "passage",
    category: "Education",
  },
  {
    id: 4,
    question:
      " What is the major difference between Nigeria and other african coutries and their neighbors",
    option: {
      'a': "Mineral  resources and culture",
      'b': "landscape ",
      'c': " a white dozen eggs ",
      'd': "dozen white cap",
    },
    passage: "most appropriate option",
    image: "",
    answer: "a",
    solution: "",
    subject: 'Mathematics',
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleOptions",
    category: "Education",
  },
  {
    id: 5,
    question: " Euglena viridis is ",
    option: {
      'a': " a plant ",
      'b': " an animal",
      'c': " I don't know ",
      'd': " None of the above",
    },

    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    subject: "Yoruba",
    modal: 'image',
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleOptions",
    category: "Education",
  },
  {
    id: 6,
    question: " Choose out of the words below ",
    option: {
      'a': "white dozen eggs ",
      'b': "a dozen white ",
      'c': " a white dozen eggs ",
      'd': "dozen white",
    },
    passage: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quis amet inventore quam? Itaque cupiditate accusantium quis. Minima, aperiam. Sed ea sapiente, hic quasi aperiam recusandae dolor repellat aspernatur corporis!",
    image: "",
    answer: "b",
    modal: 'passage',
    solution: "",
    examtype: "utme",
    subject: 'Literature in English',
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleChoice",
    category: "Education",
  },
  {
    id: 7,
    question: " Nigerian flag consists of 2 colours ",
    option: { 'a': "true ", 'b': "false " },

    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    subject: 'Literature in English',
    examyear: "2003",
    questionNub: 0,
    questionType: "trueOrFalse",
    category: "Education",
  },
  {
    id: 8,
    question: " He put_____  eggs in a basket.",
    option: {
      'a': "white dozen eggs ",
      'b': "a dozen white ",
      'c': " a white dozen eggs ",
      'd': " dozen white",
    },
    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    subject: 'English',
    examyear: "2003",
    questionNub: 0,
    questionType: "passage",
    category: "Education",
  },
  {
    id: 9,
    question:
      " What is the major difference between Nigeria and other african coutries and their neighbors",
    option: {
      'a': "Mineral  resources and culture",
      'b': "landscape ",
      'c': " a white dozen eggs ",
      'd': "dozen white cap",
    },
    passage: "most appropriate option",
    image: "",
    answer: "a",
    solution: "",
    subject: 'Mathematics',
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleOptions",
    category: "Education",
  },
  // {
  //   id: 5,
  //   question: " Euglena viridis is ",
  //   option: {
  //     'a': " a plant ",
  //     'b': " an animal",
  //     'c': " I don't know ",
  //     'd': " None of the above",
  //   },

  //   passage: "most appropriate option",
  //   image: "",
  //   answer: "b",
  //   solution: "",
  //   subject: "Mathematics",
  //   modal: 'image',
  //   examtype: "utme",
  //   examyear: "2003",
  //   questionNub: 0,
  //   questionType: "multipleOptions",
  //   category: "Education",
  // },
  // {
  //   id: 1,
  //   question: " Choose out of the words below ",
  //   option: {
  //     'a': "white dozen eggs ",
  //     'b': "a dozen white ",
  //     'c': " a white dozen eggs ",
  //     'd': "dozen white",
  //   },
  //   passage: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque quis amet inventore quam? Itaque cupiditate accusantium quis. Minima, aperiam. Sed ea sapiente, hic quasi aperiam recusandae dolor repellat aspernatur corporis!",
  //   image: "",
  //   answer: "b",
  //   modal: 'passage',
  //   solution: "",
  //   examtype: "utme",
  //   subject: 'English',
  //   examyear: "2003",
  //   questionNub: 0,
  //   questionType: "multipleChoice",
  //   category: "Education",
  // },
  // {
  //   id: 2,
  //   question: " Nigerian flag consists of 2 colours ",
  //   option: { 'a': "true ", 'b': "false " },

  //   passage: "most appropriate option",
  //   image: "",
  //   answer: "b",
  //   solution: "",
  //   examtype: "utme",
  //   examyear: "2003",
  //   questionNub: 0,
  //   questionType: "trueOrFalse",
  //   category: "Education",
  // },
  // {
  //   id: 3,
  //   question: " He put_____  eggs in a basket.",
  //   option: {
  //     'a': "white dozen eggs ",
  //     'b': "a dozen white ",
  //     'c': " a white dozen eggs ",
  //     'd': " dozen white",
  //   },
  //   passage: "most appropriate option",
  //   image: "",
  //   answer: "b",
  //   solution: "",
  //   examtype: "utme",
  //   subject: 'English',
  //   examyear: "2003",
  //   questionNub: 0,
  //   questionType: "passage",
  //   category: "Education",
  // },
  // {
  //   id: 4,
  //   question:
  //     " What is the major difference between Nigeria and other african coutries and their neighbors",
  //   option: {
  //     'a': "Mineral  resources and culture",
  //     'b': "landscape ",
  //     'c': " a white dozen eggs ",
  //     'd': "dozen white cap",
  //   },
  //   passage: "most appropriate option",
  //   image: "",
  //   answer: "a",
  //   solution: "",
  //   subject: 'Mathematics',
  //   examtype: "utme",
  //   examyear: "2003",
  //   questionNub: 0,
  //   questionType: "multipleOptions",
  //   category: "Education",
  // },
  // {
  //   id: 5,
  //   question: " Euglena viridis is ",
  //   option: {
  //     'a': " a plant ",
  //     'b': " an animal",
  //     'c': " I don't know ",
  //     'd': " None of the above",
  //   },

  //   passage: "most appropriate option",
  //   image: "",
  //   answer: "b",
  //   solution: "",
  //   subject: "Mathematics",
  //   modal: 'image',
  //   examtype: "utme",
  //   examyear: "2003",
  //   questionNub: 0,
  //   questionType: "multipleOptions",
  //   category: "Education",
  // },
  {
    id: 7,
    question: ` 'Verily Allah has prescribed the best behaviour with regard to evrything...' 
    The above quotation from Hadith No. 17 of an-Nawawi's collection emphasizes the ethics of `,
    option: {
      'a': " Eating and drinking ",
      'b': " animal slaughtering",
      'c': " Public behaviour ",
      'd': " Matrimonial relations",
    },

    passage: "",
    image: "",
    answer: "d",
    solution: "",
    subject: "Mathematics",
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleOptions",
    category: "Education",
  },
];
