export const Questions = [
  {
    id: 1,
    question: " He put________  eggs in a basket.",
    option: {
      "a": "white dozen eggs ",
      "b": "a dozen white ",
      "c": " a white dozen eggs ",
      "d": "dozen white"
    },
    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "multipleChoice",
    category: "Education",
  },
  {
    id: 2,
    question: " Nigerian flag consists of 2 colours ",
    option: [
      { key: "a", value: "true " },
      { key: "b", value: "false " },
    ],
    passage: "most appropriate option",
    image: "",
    answer: 'b',
    solution: "",
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "trueOrFalse",
    category: "Education",
  },
  {
    id: 3,
    question: " He put_____  eggs in a basket.",
    option: {
      "a": "white dozen eggs ",
      "b": "a dozen white ",
      "c": " a white dozen eggs ",
      "d": "dozen white"
    },
    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "passage",
    category: "Education",
  },
  {
    id: 4,
    question: " He put…………..  eggs in a basket.",
    option: {
      "a": "white dozen eggs ",
      "b": "a dozen white ",
      "c": " a white dozen eggs ",
      "d": "dozen white"
    },
    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "passage",
    category: "multipleOptions",
  },
  {
    id: 5,
    question: " He put…………..  eggs in a basket.",
    option: {
      "a": "white dozen eggs ",
      "b": "a dozen white ",
      "c": " a white dozen eggs ",
      "d": "dozen white"
    },
    
    passage: "most appropriate option",
    image: "",
    answer: "b",
    solution: "",
    examtype: "utme",
    examyear: "2003",
    questionNub: 0,
    questionType: "image",
    category: "Education",
  },
];
